name: Push to feature branch
on:
  push:
    branches:
      - '*'
      - '!main'

env:
  TF_LOG: INFO
  TF_INPUT: false
  TF_VERSION: 1.5.7
  TG_VERSION: v0.50.17
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: $TF_VERSION

    - name: Setup Terragrunt
      run: |
        curl -s -qL -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/$TG_VERSION/terragrunt_linux_amd64
        chmod +x terragrunt
        sudo mv terragrunt /bin  

    - name: Terragrunt Init
      id: init
      run: terragrunt run-all init

    - name: Terragrunt Format
      id: format
      run: terragrunt fmt -check -recursive diff
      continue-on-error: false

    - name: Terragrunt Validate
      id: validate
      run: terragrunt run-all validate
      continue-on-error: true