name: 'TFSec'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

env:
  WORKING_DIR: ./examples/

jobs:
  testing:
    name: 'Terraform tfsec'
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get and Report TFSec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          format: junit
          additional_args: --out tfsec-junit.xml
          working_directory: ${{ env.WORKING_DIR }}
        continue-on-error: true
      
      - name: Post TFSec Report
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        if: success() || failure()
        with:
          github_token: ${{ github.token }}
          tfsec_formats: junit
          soft_fail_commenter: true
          tfsec_args: --out=tfsec-junit.xml